### ISSUE TITLE
Code looking for settings file that does not exist on my PC

### ISSUE THREAD

**Issue by arphox** [Vampyr7878/WoW-Talent-Calculator-Classic#1]
Hi!

After downloading your code, I wanted to try it, but it could not find the (non existing) `\bin\Debug\settings.txt` file on my computer.

So this just does not work out of the box.

(This is an information for other developers rather than an issue I want to see fixed)

**Comment by Vampyr7878** [comment]
It seems something, screwed the csproj file so the project didn't remember to copy the asset files to the output dir. I have updated these settings and uploaded the changes. Should work now,

**Comment by arphox** [comment]
I tried it again and I can't build it now.
![kép](https://user-images.githubusercontent.com/17320094/63649212-35231400-c73b-11e9-8790-13eafced6080.png)

Tried clean, rebuild solution, not works.

**Comment by Vampyr7878** [comment]
I see, there were some remains after early WIP version in the file list inside csproj file. The files are long gone. I removed those and checked completely clean build. It works. Thank you for your input.

**Comment by arphox** [comment]
Works fine, thank you. :-)
